
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int div = 6;
  public static final int resta = 4;
  public static final int suma = 3;
  public static final int mult = 5;
  public static final int decimal = 8;
  public static final int EOF = 0;
  public static final int entero = 7;
  public static final int error = 1;
  public static final int nombre = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "nombre",
  "suma",
  "resta",
  "mult",
  "div",
  "entero",
  "decimal"
  };
}

